POST http://localhost:6000/products
Content-Type: application/json

{
    "nameProduct":"uhuhb",
    "categories":"Makanan",
    "madeIn":"Madiun"
}
###
DELETE http://localhost:6000/products/67593698630e55441b633bef
###

PATCH http://localhost:6000/products/63c16b0f24a11fc0dc1a591a
Content-Type: application/json

{
    "madeIn":"Semarang"
}
###
GET http://localhost:6000/products